# Generated by Django 6.0.4 on 2026-04-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habit_end_date_habit_target_daily_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together=set(),
        ),
    ]
