# Generated by Django 6.0.4 on 2026-04-22 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_habitcompletion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency_type',
            field=models.CharField(choices=[('DAILY', 'Каждый день'), ('WEEKLY', 'По дням недели'), ('INTERVAL', 'Интервал')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('is_important', models.BooleanField(default=True)),
                ('ai_motivation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
